# Actividad - Librería `pandas`

* **Nombre:** Diego Vega Camacho
* **Matrícula:** A01704492

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  
import pandas as pd
import numpy as np

Saving netflix_titles.csv to netflix_titles.csv
User uploaded file "netflix_titles.csv" with length 3000491 bytes

**Entregar:** Archivo PDF de la actividad, así como el archivo .ipynb en tu repositorio.
**Nota:** Recuerda habrá una penalización de **50** puntos si la actividad fue entregada fuera de la fecha límite.

1. Subir el archivo `netflix_titles.csv` que se encuentra en el repositorio de la clase y cargalos en un `DataFrame`.

In [6]:
df = pd.read_csv('netflix_titles.csv')

2. Desplegar las primeras 5 líneas del `DataFrame`.

In [5]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

3. Implementa una función que despliegue el primer renglon de un `DataFrame`.

In [10]:
def the_first():
  fstrow = df.head(1)
  return fstrow

the_first()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...

4. Implementa una función que regrese el número de registros en el `DataFrame`.

In [16]:
  def row_number():
    df = pd.read_csv('netflix_titles.csv')
    dr = df.iloc[0]
    return dr

5. Implementa una función que despliega las películas con un `release_year` determinado.

In [35]:
def released_year(year):
  df = pd.read_csv('netflix_titles.csv', usecols=[7])
  df3 = df[df == 2020]
  dF = df3.dropna(how='any')
  return dF

year_query = 2020
released_year(year_query)

      release_year
0           2020.0
24          2020.0
26          2020.0
27          2020.0
29          2020.0
...            ...
7725        2020.0
7734        2020.0
7738        2020.0
7741        2020.0
7744        2020.0

[868 rows x 1 columns]

6. Implementa una función que despliegue las películas que son de un país determinado.

In [36]:
def origin_country(country):
  df = pd.read_csv('netflix_titles.csv', usecols=[5])
  df3 = df[df == 'Mexico']
  dF = df3.dropna(how='any')
  return dF

country_query = 'Mexico'
origin_country(country_query)

     country
1     Mexico
12    Mexico
292   Mexico
370   Mexico
378   Mexico
...      ...
7698  Mexico
7725  Mexico
7734  Mexico
7773  Mexico
7779  Mexico

[100 rows x 1 columns]

7. Crea un nuevo `DataFrame` que sólo contenga las columnas `type`, `title`, `country` y `release_year`.

In [29]:
df = pd.read_csv('netflix_titles.csv', usecols=[1, 2, 5, 7])
df.head()

      type  title        country  release_year
0  TV Show     3%         Brazil          2020
1    Movie   7:19         Mexico          2016
2    Movie  23:59      Singapore          2011
3    Movie      9  United States          2009
4    Movie     21  United States          2008

8. Despliega, cuantos tipos de producciones (`type`) se hicieron por país determinado (`country`).

In [48]:
df = pd.read_csv('netflix_titles.csv', usecols=[1,5])
dF = df.dropna(how='any')
dF

         type                                            country
0     TV Show                                             Brazil
1       Movie                                             Mexico
2       Movie                                          Singapore
3       Movie                                      United States
4       Movie                                      United States
...       ...                                                ...
7781    Movie                                      United States
7782    Movie  Sweden, Czech Republic, United Kingdom, Denmar...
7783    Movie                                              India
7785  TV Show                                          Australia
7786    Movie              United Kingdom, Canada, United States

[7280 rows x 2 columns]

# 9. Implementa la función que genera el cuadrado de un número.

In [37]:
def square(x):
  df = pd.DataFrame
  square = df.applymap(np.square)
  return square

10. Usando el método `apply`, genera el cuadrado de todos los valores del siguiente `DataFrame`.

In [43]:
df2 = pd.DataFrame({'A': [1, 2, 3, 5, 6], 'B': [10, 20, 30, 40, 50]})
df2.apply(np.square)

    A     B
0   1   100
1   4   400
2   9   900
3  25  1600
4  36  2500